### R Lists 

**Lists** are the R objects which contain elements of different types like − numbers, strings, vectors and another list inside it.<br>
A list can also contain a matrix or a function as its elements. <br>
List is created using list() function. <br>
Lists act like just like a folder where we can organize the objects. 

#### Creating a list from various data objects

In [73]:
vec <- c(1,2,3,4)
vec1 <- c('sree', "jani", "Rani")
mat <- matrix(1:15, nrow=5)
str <- " Heloo How do you do"
num <- 123


In [74]:
# Now let us make list
my_list <- list(vec, vec1, mat, str, num)

In [75]:
my_list

[[1]]
[1] 1 2 3 4

[[2]]
[1] "sree" "jani" "Rani"

[[3]]
     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15

[[4]]
[1] " Heloo How do you do"

[[5]]
[1] 123

In [76]:
my_list[2]

[[1]]
[1] "sree" "jani" "Rani"

#### Naming the list element 

In [77]:
names(my_list) <- c("1st", "2nd", "3rd",'4th', '5th')


In [78]:
my_list

$`1st`
[1] 1 2 3 4

$`2nd`
[1] "sree" "jani" "Rani"

$`3rd`
     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15

$`4th`
[1] " Heloo How do you do"

$`5th`
[1] 123

#### Indexing the list elements

In [79]:
my_list[1]

$`1st`
[1] 1 2 3 4

In [80]:
my_list$'1st' # $ notation

[1] 1 2 3 4

In [81]:
my_list['1st'] 

$`1st`
[1] 1 2 3 4

In [82]:
class(my_list['1st']) # Note that bracket notation results a list

[1] "list"

In [83]:
class(my_list$'1st') # Note that this results a vector

[1] "numeric"

In [84]:
my_list[['1st']] # Double bracket notation

[1] 1 2 3 4

#### Merging lists into a single list

In [85]:
list1 <- list(c(1,2,3,5), matrix(1:10,nrow=5))
list2 <- list(c(1,2,8,10), 'sree', 234)
merged.list = list(list1,list2)
merged.list

[[1]]
[[1]][[1]]
[1] 1 2 3 5

[[1]][[2]]
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10


[[2]]
[[2]][[1]]
[1]  1  2  8 10

[[2]][[2]]
[1] "sree"

[[2]][[3]]
[1] 234

#### R Predefined Lists

In [86]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [87]:
LETTERS


[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [88]:
month.abb

[1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

In [89]:
month.name

[1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December"

In [90]:
# Structure of a list 
str(my_list)

List of 5
 $ 1st: num [1:4] 1 2 3 4
 $ 2nd: chr [1:3] "sree" "jani" "Rani"
 $ 3rd: int [1:5, 1:3] 1 2 3 4 5 6 7 8 9 10 ...
 $ 4th: chr " Heloo How do you do"
 $ 5th: num 123


#### Adding and Removing elements from a list

In [91]:
# Adding
my_list[['6th']] <- c(23,45,67)

In [92]:
my_list

$`1st`
[1] 1 2 3 4

$`2nd`
[1] "sree" "jani" "Rani"

$`3rd`
     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15

$`4th`
[1] " Heloo How do you do"

$`5th`
[1] 123

$`6th`
[1] 23 45 67

In [93]:
# Removing 6th object
my_list[6] <- NULL

In [94]:
my_list

$`1st`
[1] 1 2 3 4

$`2nd`
[1] "sree" "jani" "Rani"

$`3rd`
     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15

$`4th`
[1] " Heloo How do you do"

$`5th`
[1] 123