## R - Matrices 

**Matrices** are the R objects in which the elements are arranged in a two-dimensional rectangular layout. <br>
They contain elements of the same atomic types. Though we can create a matrix containing only characters or only logical values, they are not of much use. <br>
We use matrices containing numeric elements to be used in mathematical calculations.

A Matrix is created using the matrix() function.<br>
Basic Syntax:<br>

matrix(data, nrow, ncol, byrow, dimnames)


In [1]:
# Creating a matrix adding colnames, rownames 
students<- c('Raj','Ravi','Sita','Ram',"Hanuma")
attributes <- c('Age', 'Salary')
student.matrix <- c(23,25,26,32,30, 20000, 25000,26000,32000,38000)
student.matrix <- matrix(student.matrix, byrow = FALSE, ncol = 2) # Making a two column matrix.
student.matrix

[,1] [,2] 
[1,] 23   20000
[2,] 25   25000
[3,] 26   26000
[4,] 32   32000
[5,] 30   38000

In [2]:
# Now adding column and row names
colnames(student.matrix) <- attributes # Adding column names 
rownames(student.matrix) <- students # Adding row names

In [3]:
student.matrix # This now represents a table structure 

Age Salary
Raj    23  20000 
Ravi   25  25000 
Sita   26  26000 
Ram    32  32000 
Hanuma 30  38000

### Matrices arithmetic

In [4]:
# similar to vector artithmetic, element to element matrix arithmetic can be done on matrices
mat1 <- matrix(c(1:25) , byrow = TRUE, nrow = 5) # c(1:25) is creating a sequence 

In [5]:
mat1

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [6]:
mat1+mat1 # addition

[,1] [,2] [,3] [,4] [,5]
[1,]  2    4    6    8   10  
[2,] 12   14   16   18   20  
[3,] 22   24   26   28   30  
[4,] 32   34   36   38   40  
[5,] 42   44   46   48   50

In [7]:
mat1-mat1 #subtract

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0   
[2,] 0    0    0    0    0   
[3,] 0    0    0    0    0   
[4,] 0    0    0    0    0   
[5,] 0    0    0    0    0

In [8]:
mat1*2 #multiply

[,1] [,2] [,3] [,4] [,5]
[1,]  2    4    6    8   10  
[2,] 12   14   16   18   20  
[3,] 22   24   26   28   30  
[4,] 32   34   36   38   40  
[5,] 42   44   46   48   50

In [9]:
mat1/mat1 #division

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [10]:
sqrt(mat1) # Square root

[,1]     [,2]     [,3]     [,4]     [,5]    
[1,] 1.000000 1.414214 1.732051 2.000000 2.236068
[2,] 2.449490 2.645751 2.828427 3.000000 3.162278
[3,] 3.316625 3.464102 3.605551 3.741657 3.872983
[4,] 4.000000 4.123106 4.242641 4.358899 4.472136
[5,] 4.582576 4.690416 4.795832 4.898979 5.000000

In [11]:
max(mat1) # max of all elements

[1] 25

In [12]:
min(mat1) # min of all elements

[1] 1

In [13]:
mean(mat1) # mean of all elements

[1] 13

In [14]:
sum(mat1) # sum of all elements

[1] 325

### Accessing the cols, rows and individual elements of a matrix

In [23]:
# Syntax format
#matrix[rows_start:rows_end,cols_start:cols_end]

In [15]:
# grabbing 1st column
mat1[,1] 

[1]  1  6 11 16 21

In [16]:
# grabbing the 2nd row
mat1[2,]

[1]  6  7  8  9 10

In [17]:
# grabbing 3rd row, 2nd column element
mat1[3,2]


[1] 12

In [19]:
mat1[2:4,] #This grabs rows 2 to 4

[,1] [,2] [,3] [,4] [,5]
[1,]  6    7    8    9   10  
[2,] 11   12   13   14   15  
[3,] 16   17   18   19   20

In [22]:
mat1[,3:5] #This grabs column 3 to 5 

[,1] [,2] [,3]
[1,]  3    4    5  
[2,]  8    9   10  
[3,] 13   14   15  
[4,] 18   19   20  
[5,] 23   24   25

### Some Builtin Functions on Matrices

In [19]:
# Getting column sums
mat1

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [20]:
colSums(mat1) # Notice the S capital

[1] 55 60 65 70 75

In [21]:
rowSums(mat1) # Row sums

[1]  15  40  65  90 115

In [23]:
rowMeans(mat1) #Row mean

[1]  3  8 13 18 23

In [25]:
colMeans(mat1) #col Mean

[1] 11 12 13 14 15

In [26]:
#Getting a column max
max(mat1[,2])

[1] 22

In [27]:
# getting a row max 
max(mat1[2,])

[1] 10

In [29]:
student.matrix

Age Salary
Raj    23  20000 
Ravi   25  25000 
Sita   26  26000 
Ram    32  32000 
Hanuma 30  38000

### rbind , cbind 

In [30]:
#Adding a row to the matrix with rbind
student.matrix

Age Salary
Raj    23  20000 
Ravi   25  25000 
Sita   26  26000 
Ram    32  32000 
Hanuma 30  38000

In [38]:
Hema <- c(32, 25000)
student.matrix <- rbind(student.matrix, Hema)

In [42]:
Tax <- student.matrix[,2]*0.1

In [43]:
Tax

Raj   Ravi   Sita    Ram Hanuma   Hema 
  2000   2500   2600   3200   3800   2500

In [46]:
student.matrix <- cbind(student.matrix,Tax) # Adding t
student.matrix

Age Salary Tax  Tax 
Raj    23  20000  2000 2000
Ravi   25  25000  2500 2500
Sita   26  26000  2600 2600
Ram    32  32000  3200 3200
Hanuma 30  38000  3800 3800
Hema   32  25000  2500 2500